# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2cc6116109964660ec582d9ac7df3b01c44fd38c4e38b640a12f696fa9e786ec4cee1eb1683f8a1967974f827c50d6b14df4cb52227ef7d75dcff9ab3f126a9

test:
  secret_key_base: a08f0bfb54eed870d37cb241e550f7d5746a6ddb46eba006d30ed94aa301fd2b08f4d864cbf3369e6aba5ac8f1df5dadd040b7e4509dae6c3ab448ce58358917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
